language: rust

rust:
  - stable

cache: cargo

before_install:
  - sudo apt-get install -y libarchive-dev

before_script:
  - rustup component add clippy
  - rustup component add rustfmt

script:
  - cargo check --verbose --all
  - cargo check --verbose --all --features=libalpm
  - cargo clippy --all-targets --features= -- -D warnings
  - cargo fmt --all -- --check
  - shellcheck -e SC1090 res/*.sh  # exclude non-constant sourcing that shellcheck cannot check

if: tag IS blank  # do not build tags, only commits

sudo: false

notifications:
  email:
    on_success: change
    on_failure: always
