[package]
name = "rua"
version = "0.18.1"
description = "Secure jailed AUR helper for Arch Linux"
authors = [
  "Vasili Novikov <n1dr+cm3513git@yandex.ru>",
  "Stefano Probst <senden9@gmail.com>",
  "morganamilo <morganamilo@gmail.com>",
  "nolik <Novik030692!>",
  "Aaron Cunningham <aa.cunningham@outlook.com>",
  "VukoDrakkeinen <sneyk8+git@gmail.com>",
  "Markus Richter <8398165+mqus@users.noreply.github.com>",
]
license="GPL-3.0-or-later"
edition="2018"
keywords = ["archlinux", "aur", "build", "jail", "bubblewrap"]
readme = "README.md"
repository = "https://github.com/vn971/rua"
build = "build.rs"

[features]
libalpm = ["alpm"]  # will use library bindings to libalpm instead of shelling (calling `pacman` executable)
libalpmgit = ["libalpm", "alpm/git"]
libalpmgenerate = ["libalpm", "alpm/generate"]

[build-dependencies]
structopt = "0.3.23"
libscmp = "0.2.0"

[dependencies]
alpm = { version = "2.1.1", default-features = false, features = [], optional = true }
anyhow = "1.0.44"
chrono = "0.4.19"
colored = "2.0.0"
directories = "4.0.1"
env_logger = "0.9.0"
fs2 = "0.4.3"
fs_extra = "1.2.0"
indexmap = "1.7.0"
itertools = "0.10.1"
lazy_static = "1.4.0"
libc = "0.2.102"
libflate = "1.1.1"
log = "0.4.14"
prettytable-rs = "0.8.0"
raur = { version = "5.0.1", default-features = false, features = ["blocking", "rustls"] }
regex = "1.5.4"
rm_rf = "0.6.1"
ruzstd = "0.2.4"
srcinfo = "1.0.0"
structopt = "0.3.23"
tar = "0.4.37"
term_size = "0.3.2"
uname = "0.1.1"
users = "0.11.0"
xz2 = "0.1.6"

[profile.release]
lto = true
